/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VespasianoRouteImport } from './routes/vespasiano'
import { Route as TransporteRouteImport } from './routes/transporte'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosPublicosRouteImport } from './routes/servicos-publicos'
import { Route as RoteiroTuristicoRouteImport } from './routes/roteiro-turistico'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReputacaoRouteImport } from './routes/reputacao'
import { Route as RepresentantesRouteImport } from './routes/representantes'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as OQueFazerRouteImport } from './routes/o-que-fazer'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EmpregosRouteImport } from './routes/empregos'
import { Route as EmergenciaRouteImport } from './routes/emergencia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as AgoraRouteImport } from './routes/agora'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepresentantesIndexRouteImport } from './routes/representantes.index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TransporteLinhasRouteImport } from './routes/transporte.linhas'
import { Route as RepresentantesRankingRouteImport } from './routes/representantes.ranking'
import { Route as RepresentantesFeedRouteImport } from './routes/representantes.feed'
import { Route as RepresentantesIdRouteImport } from './routes/representantes.$id'
import { Route as PainelRankingRouteImport } from './routes/painel.ranking'
import { Route as PainelPromocoesRouteImport } from './routes/painel.promocoes'
import { Route as PainelPerfilRouteImport } from './routes/painel.perfil'
import { Route as PainelNotificacoesRouteImport } from './routes/painel.notificacoes'
import { Route as PainelMensagensRouteImport } from './routes/painel.mensagens'
import { Route as PainelLeadsRouteImport } from './routes/painel.leads'
import { Route as PainelFavoritosRouteImport } from './routes/painel.favoritos'
import { Route as PainelEmpresasRouteImport } from './routes/painel.empresas'
import { Route as PainelAvaliacoesRouteImport } from './routes/painel.avaliacoes'
import { Route as PainelAnunciosRouteImport } from './routes/painel.anuncios'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as EmpresaSlugRouteImport } from './routes/empresa.$slug'
import { Route as EmpregosPremiumRouteImport } from './routes/empregos.premium'
import { Route as EmpregosIdRouteImport } from './routes/empregos.$id'
import { Route as CidadesSlugRouteImport } from './routes/cidades.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTurismoRouteImport } from './routes/admin.turismo'
import { Route as AdminTextosRouteImport } from './routes/admin.textos'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AdminServicosPublicosRouteImport } from './routes/admin.servicos-publicos'
import { Route as AdminScraperVespasianoRouteImport } from './routes/admin.scraper-vespasiano'
import { Route as AdminScraperSjlRouteImport } from './routes/admin.scraper-sjl'
import { Route as AdminScraperCamaraSjlRouteImport } from './routes/admin.scraper-camara-sjl'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminPushRouteImport } from './routes/admin.push'
import { Route as AdminPromocoesRouteImport } from './routes/admin.promocoes'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminEmpregosRouteImport } from './routes/admin.empregos'
import { Route as AdminEmergenciaRouteImport } from './routes/admin.emergencia'
import { Route as AdminDuplicadosRouteImport } from './routes/admin.duplicados'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCidadesRouteImport } from './routes/admin.cidades'
import { Route as AdminCalendarioEditorialRouteImport } from './routes/admin.calendario-editorial'
import { Route as AdminBlogAiRouteImport } from './routes/admin.blog-ai'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAoVivoRouteImport } from './routes/admin.ao-vivo'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as AdminAnalyticsAnunciosRouteImport } from './routes/admin.analytics-anuncios'
import { Route as AdminPushIndexRouteImport } from './routes/admin.push.index'
import { Route as PainelNotificacoesPreferenciasRouteImport } from './routes/painel.notificacoes.preferencias'
import { Route as PainelEmpresasNovaRouteImport } from './routes/painel.empresas.nova'
import { Route as PainelEmpresasIdRouteImport } from './routes/painel.empresas.$id'
import { Route as PainelAnunciosNovoRouteImport } from './routes/painel.anuncios.novo'
import { Route as AdminPushTemplatesRouteImport } from './routes/admin.push.templates'
import { Route as AdminPushNovoRouteImport } from './routes/admin.push.novo'
import { Route as AdminPushHistoricoRouteImport } from './routes/admin.push.historico'
import { Route as AdminPushIdRouteImport } from './routes/admin.push.$id'
import { Route as PainelAnunciosIdEditarRouteImport } from './routes/painel.anuncios.$id.editar'
import { Route as ApiPublicPushTrackRouteImport } from './routes/api/public/push/track'
import { Route as ApiPublicPushResubscribeRouteImport } from './routes/api/public/push/resubscribe'
import { Route as ApiPublicHooksWhatsappWeeklyDigestRouteImport } from './routes/api/public/hooks/whatsapp-weekly-digest'
import { Route as ApiPublicHooksWhatsappOptOutRouteImport } from './routes/api/public/hooks/whatsapp-opt-out'
import { Route as ApiPublicHooksSyncRepresentativesRouteImport } from './routes/api/public/hooks/sync-representatives'
import { Route as ApiPublicHooksSyncOriginalRouteImport } from './routes/api/public/hooks/sync-original'
import { Route as ApiPublicHooksSyncBusRouteImport } from './routes/api/public/hooks/sync-bus'
import { Route as ApiPublicHooksScrapeServicesRouteImport } from './routes/api/public/hooks/scrape-services'
import { Route as ApiPublicHooksScrapeProcurementsRouteImport } from './routes/api/public/hooks/scrape-procurements'
import { Route as ApiPublicHooksScrapeEventsRouteImport } from './routes/api/public/hooks/scrape-events'
import { Route as ApiPublicHooksPushSchedulerRouteImport } from './routes/api/public/hooks/push-scheduler'
import { Route as ApiPublicHooksJobsSyncRouteImport } from './routes/api/public/hooks/jobs-sync'
import { Route as ApiPublicHooksDailyBlogPostRouteImport } from './routes/api/public/hooks/daily-blog-post'

const VespasianoRoute = VespasianoRouteImport.update({
  id: '/vespasiano',
  path: '/vespasiano',
  getParentRoute: () => rootRouteImport,
} as any)
const TransporteRoute = TransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPublicosRoute = ServicosPublicosRouteImport.update({
  id: '/servicos-publicos',
  path: '/servicos-publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteiroTuristicoRoute = RoteiroTuristicoRouteImport.update({
  id: '/roteiro-turistico',
  path: '/roteiro-turistico',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReputacaoRoute = ReputacaoRouteImport.update({
  id: '/reputacao',
  path: '/reputacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesRoute = RepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazerRoute = OQueFazerRouteImport.update({
  id: '/o-que-fazer',
  path: '/o-que-fazer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpregosRoute = EmpregosRouteImport.update({
  id: '/empregos',
  path: '/empregos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaRoute = EmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgoraRoute = AgoraRouteImport.update({
  id: '/agora',
  path: '/agora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesIndexRoute = RepresentantesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepresentantesRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TransporteLinhasRoute = TransporteLinhasRouteImport.update({
  id: '/linhas',
  path: '/linhas',
  getParentRoute: () => TransporteRoute,
} as any)
const RepresentantesRankingRoute = RepresentantesRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => RepresentantesRoute,
} as any)
const RepresentantesFeedRoute = RepresentantesFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => RepresentantesRoute,
} as any)
const RepresentantesIdRoute = RepresentantesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepresentantesRoute,
} as any)
const PainelRankingRoute = PainelRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPromocoesRoute = PainelPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNotificacoesRoute = PainelNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMensagensRoute = PainelMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => PainelRoute,
} as any)
const PainelLeadsRoute = PainelLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFavoritosRoute = PainelFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEmpresasRoute = PainelEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAvaliacoesRoute = PainelAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAnunciosRoute = PainelAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => PainelRoute,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaSlugRoute = EmpresaSlugRouteImport.update({
  id: '/empresa/$slug',
  path: '/empresa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpregosPremiumRoute = EmpregosPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => EmpregosRoute,
} as any)
const EmpregosIdRoute = EmpregosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpregosRoute,
} as any)
const CidadesSlugRoute = CidadesSlugRouteImport.update({
  id: '/cidades/$slug',
  path: '/cidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTurismoRoute = AdminTurismoRouteImport.update({
  id: '/turismo',
  path: '/turismo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTextosRoute = AdminTextosRouteImport.update({
  id: '/textos',
  path: '/textos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosPublicosRoute = AdminServicosPublicosRouteImport.update({
  id: '/servicos-publicos',
  path: '/servicos-publicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScraperVespasianoRoute = AdminScraperVespasianoRouteImport.update({
  id: '/scraper-vespasiano',
  path: '/scraper-vespasiano',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScraperSjlRoute = AdminScraperSjlRouteImport.update({
  id: '/scraper-sjl',
  path: '/scraper-sjl',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScraperCamaraSjlRoute = AdminScraperCamaraSjlRouteImport.update({
  id: '/scraper-camara-sjl',
  path: '/scraper-camara-sjl',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPushRoute = AdminPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpregosRoute = AdminEmpregosRouteImport.update({
  id: '/empregos',
  path: '/empregos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergenciaRoute = AdminEmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuplicadosRoute = AdminDuplicadosRouteImport.update({
  id: '/duplicados',
  path: '/duplicados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCidadesRoute = AdminCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioEditorialRoute =
  AdminCalendarioEditorialRouteImport.update({
    id: '/calendario-editorial',
    path: '/calendario-editorial',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogAiRoute = AdminBlogAiRouteImport.update({
  id: '/blog-ai',
  path: '/blog-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAoVivoRoute = AdminAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsAnunciosRoute = AdminAnalyticsAnunciosRouteImport.update({
  id: '/analytics-anuncios',
  path: '/analytics-anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPushIndexRoute = AdminPushIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPushRoute,
} as any)
const PainelNotificacoesPreferenciasRoute =
  PainelNotificacoesPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => PainelNotificacoesRoute,
  } as any)
const PainelEmpresasNovaRoute = PainelEmpresasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => PainelEmpresasRoute,
} as any)
const PainelEmpresasIdRoute = PainelEmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PainelEmpresasRoute,
} as any)
const PainelAnunciosNovoRoute = PainelAnunciosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PainelAnunciosRoute,
} as any)
const AdminPushTemplatesRoute = AdminPushTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminPushRoute,
} as any)
const AdminPushNovoRoute = AdminPushNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminPushRoute,
} as any)
const AdminPushHistoricoRoute = AdminPushHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminPushRoute,
} as any)
const AdminPushIdRoute = AdminPushIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPushRoute,
} as any)
const PainelAnunciosIdEditarRoute = PainelAnunciosIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => PainelAnunciosRoute,
} as any)
const ApiPublicPushTrackRoute = ApiPublicPushTrackRouteImport.update({
  id: '/api/public/push/track',
  path: '/api/public/push/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushResubscribeRoute =
  ApiPublicPushResubscribeRouteImport.update({
    id: '/api/public/push/resubscribe',
    path: '/api/public/push/resubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappWeeklyDigestRoute =
  ApiPublicHooksWhatsappWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/whatsapp-weekly-digest',
    path: '/api/public/hooks/whatsapp-weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappOptOutRoute =
  ApiPublicHooksWhatsappOptOutRouteImport.update({
    id: '/api/public/hooks/whatsapp-opt-out',
    path: '/api/public/hooks/whatsapp-opt-out',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncRepresentativesRoute =
  ApiPublicHooksSyncRepresentativesRouteImport.update({
    id: '/api/public/hooks/sync-representatives',
    path: '/api/public/hooks/sync-representatives',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncOriginalRoute =
  ApiPublicHooksSyncOriginalRouteImport.update({
    id: '/api/public/hooks/sync-original',
    path: '/api/public/hooks/sync-original',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBusRoute = ApiPublicHooksSyncBusRouteImport.update({
  id: '/api/public/hooks/sync-bus',
  path: '/api/public/hooks/sync-bus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeServicesRoute =
  ApiPublicHooksScrapeServicesRouteImport.update({
    id: '/api/public/hooks/scrape-services',
    path: '/api/public/hooks/scrape-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScrapeProcurementsRoute =
  ApiPublicHooksScrapeProcurementsRouteImport.update({
    id: '/api/public/hooks/scrape-procurements',
    path: '/api/public/hooks/scrape-procurements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScrapeEventsRoute =
  ApiPublicHooksScrapeEventsRouteImport.update({
    id: '/api/public/hooks/scrape-events',
    path: '/api/public/hooks/scrape-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushSchedulerRoute =
  ApiPublicHooksPushSchedulerRouteImport.update({
    id: '/api/public/hooks/push-scheduler',
    path: '/api/public/hooks/push-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksJobsSyncRoute = ApiPublicHooksJobsSyncRouteImport.update({
  id: '/api/public/hooks/jobs-sync',
  path: '/api/public/hooks/jobs-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyBlogPostRoute =
  ApiPublicHooksDailyBlogPostRouteImport.update({
    id: '/api/public/hooks/daily-blog-post',
    path: '/api/public/hooks/daily-blog-post',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agora': typeof AgoraRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/emergencia': typeof EmergenciaRoute
  '/empregos': typeof EmpregosRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/o-que-fazer': typeof OQueFazerRoute
  '/painel': typeof PainelRouteWithChildren
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/representantes': typeof RepresentantesRouteWithChildren
  '/reputacao': typeof ReputacaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roteiro-turistico': typeof RoteiroTuristicoRoute
  '/servicos-publicos': typeof ServicosPublicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/transporte': typeof TransporteRouteWithChildren
  '/vespasiano': typeof VespasianoRoute
  '/admin/analytics-anuncios': typeof AdminAnalyticsAnunciosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-ai': typeof AdminBlogAiRoute
  '/admin/calendario-editorial': typeof AdminCalendarioEditorialRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/duplicados': typeof AdminDuplicadosRoute
  '/admin/emergencia': typeof AdminEmergenciaRoute
  '/admin/empregos': typeof AdminEmpregosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/push': typeof AdminPushRouteWithChildren
  '/admin/qa': typeof AdminQaRoute
  '/admin/scraper-camara-sjl': typeof AdminScraperCamaraSjlRoute
  '/admin/scraper-sjl': typeof AdminScraperSjlRoute
  '/admin/scraper-vespasiano': typeof AdminScraperVespasianoRoute
  '/admin/servicos-publicos': typeof AdminServicosPublicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/textos': typeof AdminTextosRoute
  '/admin/turismo': typeof AdminTurismoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidades/$slug': typeof CidadesSlugRoute
  '/empregos/$id': typeof EmpregosIdRoute
  '/empregos/premium': typeof EmpregosPremiumRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/painel/anuncios': typeof PainelAnunciosRouteWithChildren
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/empresas': typeof PainelEmpresasRouteWithChildren
  '/painel/favoritos': typeof PainelFavoritosRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/mensagens': typeof PainelMensagensRoute
  '/painel/notificacoes': typeof PainelNotificacoesRouteWithChildren
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/ranking': typeof PainelRankingRoute
  '/representantes/$id': typeof RepresentantesIdRoute
  '/representantes/feed': typeof RepresentantesFeedRoute
  '/representantes/ranking': typeof RepresentantesRankingRoute
  '/transporte/linhas': typeof TransporteLinhasRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/representantes/': typeof RepresentantesIndexRoute
  '/admin/push/$id': typeof AdminPushIdRoute
  '/admin/push/historico': typeof AdminPushHistoricoRoute
  '/admin/push/novo': typeof AdminPushNovoRoute
  '/admin/push/templates': typeof AdminPushTemplatesRoute
  '/painel/anuncios/novo': typeof PainelAnunciosNovoRoute
  '/painel/empresas/$id': typeof PainelEmpresasIdRoute
  '/painel/empresas/nova': typeof PainelEmpresasNovaRoute
  '/painel/notificacoes/preferencias': typeof PainelNotificacoesPreferenciasRoute
  '/admin/push/': typeof AdminPushIndexRoute
  '/api/public/hooks/daily-blog-post': typeof ApiPublicHooksDailyBlogPostRoute
  '/api/public/hooks/jobs-sync': typeof ApiPublicHooksJobsSyncRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/api/public/hooks/scrape-events': typeof ApiPublicHooksScrapeEventsRoute
  '/api/public/hooks/scrape-procurements': typeof ApiPublicHooksScrapeProcurementsRoute
  '/api/public/hooks/scrape-services': typeof ApiPublicHooksScrapeServicesRoute
  '/api/public/hooks/sync-bus': typeof ApiPublicHooksSyncBusRoute
  '/api/public/hooks/sync-original': typeof ApiPublicHooksSyncOriginalRoute
  '/api/public/hooks/sync-representatives': typeof ApiPublicHooksSyncRepresentativesRoute
  '/api/public/hooks/whatsapp-opt-out': typeof ApiPublicHooksWhatsappOptOutRoute
  '/api/public/hooks/whatsapp-weekly-digest': typeof ApiPublicHooksWhatsappWeeklyDigestRoute
  '/api/public/push/resubscribe': typeof ApiPublicPushResubscribeRoute
  '/api/public/push/track': typeof ApiPublicPushTrackRoute
  '/painel/anuncios/$id/editar': typeof PainelAnunciosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agora': typeof AgoraRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/emergencia': typeof EmergenciaRoute
  '/empregos': typeof EmpregosRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/o-que-fazer': typeof OQueFazerRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/reputacao': typeof ReputacaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roteiro-turistico': typeof RoteiroTuristicoRoute
  '/servicos-publicos': typeof ServicosPublicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/transporte': typeof TransporteRouteWithChildren
  '/vespasiano': typeof VespasianoRoute
  '/admin/analytics-anuncios': typeof AdminAnalyticsAnunciosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-ai': typeof AdminBlogAiRoute
  '/admin/calendario-editorial': typeof AdminCalendarioEditorialRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/duplicados': typeof AdminDuplicadosRoute
  '/admin/emergencia': typeof AdminEmergenciaRoute
  '/admin/empregos': typeof AdminEmpregosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/scraper-camara-sjl': typeof AdminScraperCamaraSjlRoute
  '/admin/scraper-sjl': typeof AdminScraperSjlRoute
  '/admin/scraper-vespasiano': typeof AdminScraperVespasianoRoute
  '/admin/servicos-publicos': typeof AdminServicosPublicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/textos': typeof AdminTextosRoute
  '/admin/turismo': typeof AdminTurismoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidades/$slug': typeof CidadesSlugRoute
  '/empregos/$id': typeof EmpregosIdRoute
  '/empregos/premium': typeof EmpregosPremiumRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/painel/anuncios': typeof PainelAnunciosRouteWithChildren
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/empresas': typeof PainelEmpresasRouteWithChildren
  '/painel/favoritos': typeof PainelFavoritosRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/mensagens': typeof PainelMensagensRoute
  '/painel/notificacoes': typeof PainelNotificacoesRouteWithChildren
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/ranking': typeof PainelRankingRoute
  '/representantes/$id': typeof RepresentantesIdRoute
  '/representantes/feed': typeof RepresentantesFeedRoute
  '/representantes/ranking': typeof RepresentantesRankingRoute
  '/transporte/linhas': typeof TransporteLinhasRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/painel': typeof PainelIndexRoute
  '/representantes': typeof RepresentantesIndexRoute
  '/admin/push/$id': typeof AdminPushIdRoute
  '/admin/push/historico': typeof AdminPushHistoricoRoute
  '/admin/push/novo': typeof AdminPushNovoRoute
  '/admin/push/templates': typeof AdminPushTemplatesRoute
  '/painel/anuncios/novo': typeof PainelAnunciosNovoRoute
  '/painel/empresas/$id': typeof PainelEmpresasIdRoute
  '/painel/empresas/nova': typeof PainelEmpresasNovaRoute
  '/painel/notificacoes/preferencias': typeof PainelNotificacoesPreferenciasRoute
  '/admin/push': typeof AdminPushIndexRoute
  '/api/public/hooks/daily-blog-post': typeof ApiPublicHooksDailyBlogPostRoute
  '/api/public/hooks/jobs-sync': typeof ApiPublicHooksJobsSyncRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/api/public/hooks/scrape-events': typeof ApiPublicHooksScrapeEventsRoute
  '/api/public/hooks/scrape-procurements': typeof ApiPublicHooksScrapeProcurementsRoute
  '/api/public/hooks/scrape-services': typeof ApiPublicHooksScrapeServicesRoute
  '/api/public/hooks/sync-bus': typeof ApiPublicHooksSyncBusRoute
  '/api/public/hooks/sync-original': typeof ApiPublicHooksSyncOriginalRoute
  '/api/public/hooks/sync-representatives': typeof ApiPublicHooksSyncRepresentativesRoute
  '/api/public/hooks/whatsapp-opt-out': typeof ApiPublicHooksWhatsappOptOutRoute
  '/api/public/hooks/whatsapp-weekly-digest': typeof ApiPublicHooksWhatsappWeeklyDigestRoute
  '/api/public/push/resubscribe': typeof ApiPublicPushResubscribeRoute
  '/api/public/push/track': typeof ApiPublicPushTrackRoute
  '/painel/anuncios/$id/editar': typeof PainelAnunciosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agora': typeof AgoraRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/emergencia': typeof EmergenciaRoute
  '/empregos': typeof EmpregosRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/o-que-fazer': typeof OQueFazerRoute
  '/painel': typeof PainelRouteWithChildren
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/representantes': typeof RepresentantesRouteWithChildren
  '/reputacao': typeof ReputacaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roteiro-turistico': typeof RoteiroTuristicoRoute
  '/servicos-publicos': typeof ServicosPublicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/transporte': typeof TransporteRouteWithChildren
  '/vespasiano': typeof VespasianoRoute
  '/admin/analytics-anuncios': typeof AdminAnalyticsAnunciosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-ai': typeof AdminBlogAiRoute
  '/admin/calendario-editorial': typeof AdminCalendarioEditorialRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/duplicados': typeof AdminDuplicadosRoute
  '/admin/emergencia': typeof AdminEmergenciaRoute
  '/admin/empregos': typeof AdminEmpregosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/push': typeof AdminPushRouteWithChildren
  '/admin/qa': typeof AdminQaRoute
  '/admin/scraper-camara-sjl': typeof AdminScraperCamaraSjlRoute
  '/admin/scraper-sjl': typeof AdminScraperSjlRoute
  '/admin/scraper-vespasiano': typeof AdminScraperVespasianoRoute
  '/admin/servicos-publicos': typeof AdminServicosPublicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/textos': typeof AdminTextosRoute
  '/admin/turismo': typeof AdminTurismoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidades/$slug': typeof CidadesSlugRoute
  '/empregos/$id': typeof EmpregosIdRoute
  '/empregos/premium': typeof EmpregosPremiumRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/painel/anuncios': typeof PainelAnunciosRouteWithChildren
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/empresas': typeof PainelEmpresasRouteWithChildren
  '/painel/favoritos': typeof PainelFavoritosRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/mensagens': typeof PainelMensagensRoute
  '/painel/notificacoes': typeof PainelNotificacoesRouteWithChildren
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/ranking': typeof PainelRankingRoute
  '/representantes/$id': typeof RepresentantesIdRoute
  '/representantes/feed': typeof RepresentantesFeedRoute
  '/representantes/ranking': typeof RepresentantesRankingRoute
  '/transporte/linhas': typeof TransporteLinhasRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/representantes/': typeof RepresentantesIndexRoute
  '/admin/push/$id': typeof AdminPushIdRoute
  '/admin/push/historico': typeof AdminPushHistoricoRoute
  '/admin/push/novo': typeof AdminPushNovoRoute
  '/admin/push/templates': typeof AdminPushTemplatesRoute
  '/painel/anuncios/novo': typeof PainelAnunciosNovoRoute
  '/painel/empresas/$id': typeof PainelEmpresasIdRoute
  '/painel/empresas/nova': typeof PainelEmpresasNovaRoute
  '/painel/notificacoes/preferencias': typeof PainelNotificacoesPreferenciasRoute
  '/admin/push/': typeof AdminPushIndexRoute
  '/api/public/hooks/daily-blog-post': typeof ApiPublicHooksDailyBlogPostRoute
  '/api/public/hooks/jobs-sync': typeof ApiPublicHooksJobsSyncRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/api/public/hooks/scrape-events': typeof ApiPublicHooksScrapeEventsRoute
  '/api/public/hooks/scrape-procurements': typeof ApiPublicHooksScrapeProcurementsRoute
  '/api/public/hooks/scrape-services': typeof ApiPublicHooksScrapeServicesRoute
  '/api/public/hooks/sync-bus': typeof ApiPublicHooksSyncBusRoute
  '/api/public/hooks/sync-original': typeof ApiPublicHooksSyncOriginalRoute
  '/api/public/hooks/sync-representatives': typeof ApiPublicHooksSyncRepresentativesRoute
  '/api/public/hooks/whatsapp-opt-out': typeof ApiPublicHooksWhatsappOptOutRoute
  '/api/public/hooks/whatsapp-weekly-digest': typeof ApiPublicHooksWhatsappWeeklyDigestRoute
  '/api/public/push/resubscribe': typeof ApiPublicPushResubscribeRoute
  '/api/public/push/track': typeof ApiPublicPushTrackRoute
  '/painel/anuncios/$id/editar': typeof PainelAnunciosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agora'
    | '/ao-vivo'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/emergencia'
    | '/empregos'
    | '/favoritos'
    | '/marketplace'
    | '/o-que-fazer'
    | '/painel'
    | '/planos'
    | '/promocoes'
    | '/representantes'
    | '/reputacao'
    | '/reset-password'
    | '/roteiro-turistico'
    | '/servicos-publicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/transparencia'
    | '/transporte'
    | '/vespasiano'
    | '/admin/analytics-anuncios'
    | '/admin/anuncios'
    | '/admin/ao-vivo'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/blog-ai'
    | '/admin/calendario-editorial'
    | '/admin/cidades'
    | '/admin/configuracoes'
    | '/admin/duplicados'
    | '/admin/emergencia'
    | '/admin/empregos'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/leads'
    | '/admin/menu'
    | '/admin/planos'
    | '/admin/promocoes'
    | '/admin/push'
    | '/admin/qa'
    | '/admin/scraper-camara-sjl'
    | '/admin/scraper-sjl'
    | '/admin/scraper-vespasiano'
    | '/admin/servicos-publicos'
    | '/admin/solicitacoes'
    | '/admin/textos'
    | '/admin/turismo'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/cidades/$slug'
    | '/empregos/$id'
    | '/empregos/premium'
    | '/empresa/$slug'
    | '/eventos/$slug'
    | '/marketplace/$slug'
    | '/painel/anuncios'
    | '/painel/avaliacoes'
    | '/painel/empresas'
    | '/painel/favoritos'
    | '/painel/leads'
    | '/painel/mensagens'
    | '/painel/notificacoes'
    | '/painel/perfil'
    | '/painel/promocoes'
    | '/painel/ranking'
    | '/representantes/$id'
    | '/representantes/feed'
    | '/representantes/ranking'
    | '/transporte/linhas'
    | '/admin/'
    | '/blog/'
    | '/eventos/'
    | '/painel/'
    | '/representantes/'
    | '/admin/push/$id'
    | '/admin/push/historico'
    | '/admin/push/novo'
    | '/admin/push/templates'
    | '/painel/anuncios/novo'
    | '/painel/empresas/$id'
    | '/painel/empresas/nova'
    | '/painel/notificacoes/preferencias'
    | '/admin/push/'
    | '/api/public/hooks/daily-blog-post'
    | '/api/public/hooks/jobs-sync'
    | '/api/public/hooks/push-scheduler'
    | '/api/public/hooks/scrape-events'
    | '/api/public/hooks/scrape-procurements'
    | '/api/public/hooks/scrape-services'
    | '/api/public/hooks/sync-bus'
    | '/api/public/hooks/sync-original'
    | '/api/public/hooks/sync-representatives'
    | '/api/public/hooks/whatsapp-opt-out'
    | '/api/public/hooks/whatsapp-weekly-digest'
    | '/api/public/push/resubscribe'
    | '/api/public/push/track'
    | '/painel/anuncios/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agora'
    | '/ao-vivo'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/emergencia'
    | '/empregos'
    | '/favoritos'
    | '/marketplace'
    | '/o-que-fazer'
    | '/planos'
    | '/promocoes'
    | '/reputacao'
    | '/reset-password'
    | '/roteiro-turistico'
    | '/servicos-publicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/transparencia'
    | '/transporte'
    | '/vespasiano'
    | '/admin/analytics-anuncios'
    | '/admin/anuncios'
    | '/admin/ao-vivo'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/blog-ai'
    | '/admin/calendario-editorial'
    | '/admin/cidades'
    | '/admin/configuracoes'
    | '/admin/duplicados'
    | '/admin/emergencia'
    | '/admin/empregos'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/leads'
    | '/admin/menu'
    | '/admin/planos'
    | '/admin/promocoes'
    | '/admin/qa'
    | '/admin/scraper-camara-sjl'
    | '/admin/scraper-sjl'
    | '/admin/scraper-vespasiano'
    | '/admin/servicos-publicos'
    | '/admin/solicitacoes'
    | '/admin/textos'
    | '/admin/turismo'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/cidades/$slug'
    | '/empregos/$id'
    | '/empregos/premium'
    | '/empresa/$slug'
    | '/eventos/$slug'
    | '/marketplace/$slug'
    | '/painel/anuncios'
    | '/painel/avaliacoes'
    | '/painel/empresas'
    | '/painel/favoritos'
    | '/painel/leads'
    | '/painel/mensagens'
    | '/painel/notificacoes'
    | '/painel/perfil'
    | '/painel/promocoes'
    | '/painel/ranking'
    | '/representantes/$id'
    | '/representantes/feed'
    | '/representantes/ranking'
    | '/transporte/linhas'
    | '/admin'
    | '/blog'
    | '/eventos'
    | '/painel'
    | '/representantes'
    | '/admin/push/$id'
    | '/admin/push/historico'
    | '/admin/push/novo'
    | '/admin/push/templates'
    | '/painel/anuncios/novo'
    | '/painel/empresas/$id'
    | '/painel/empresas/nova'
    | '/painel/notificacoes/preferencias'
    | '/admin/push'
    | '/api/public/hooks/daily-blog-post'
    | '/api/public/hooks/jobs-sync'
    | '/api/public/hooks/push-scheduler'
    | '/api/public/hooks/scrape-events'
    | '/api/public/hooks/scrape-procurements'
    | '/api/public/hooks/scrape-services'
    | '/api/public/hooks/sync-bus'
    | '/api/public/hooks/sync-original'
    | '/api/public/hooks/sync-representatives'
    | '/api/public/hooks/whatsapp-opt-out'
    | '/api/public/hooks/whatsapp-weekly-digest'
    | '/api/public/push/resubscribe'
    | '/api/public/push/track'
    | '/painel/anuncios/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agora'
    | '/ao-vivo'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/emergencia'
    | '/empregos'
    | '/favoritos'
    | '/marketplace'
    | '/o-que-fazer'
    | '/painel'
    | '/planos'
    | '/promocoes'
    | '/representantes'
    | '/reputacao'
    | '/reset-password'
    | '/roteiro-turistico'
    | '/servicos-publicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/transparencia'
    | '/transporte'
    | '/vespasiano'
    | '/admin/analytics-anuncios'
    | '/admin/anuncios'
    | '/admin/ao-vivo'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/blog-ai'
    | '/admin/calendario-editorial'
    | '/admin/cidades'
    | '/admin/configuracoes'
    | '/admin/duplicados'
    | '/admin/emergencia'
    | '/admin/empregos'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/leads'
    | '/admin/menu'
    | '/admin/planos'
    | '/admin/promocoes'
    | '/admin/push'
    | '/admin/qa'
    | '/admin/scraper-camara-sjl'
    | '/admin/scraper-sjl'
    | '/admin/scraper-vespasiano'
    | '/admin/servicos-publicos'
    | '/admin/solicitacoes'
    | '/admin/textos'
    | '/admin/turismo'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/cidades/$slug'
    | '/empregos/$id'
    | '/empregos/premium'
    | '/empresa/$slug'
    | '/eventos/$slug'
    | '/marketplace/$slug'
    | '/painel/anuncios'
    | '/painel/avaliacoes'
    | '/painel/empresas'
    | '/painel/favoritos'
    | '/painel/leads'
    | '/painel/mensagens'
    | '/painel/notificacoes'
    | '/painel/perfil'
    | '/painel/promocoes'
    | '/painel/ranking'
    | '/representantes/$id'
    | '/representantes/feed'
    | '/representantes/ranking'
    | '/transporte/linhas'
    | '/admin/'
    | '/blog/'
    | '/eventos/'
    | '/painel/'
    | '/representantes/'
    | '/admin/push/$id'
    | '/admin/push/historico'
    | '/admin/push/novo'
    | '/admin/push/templates'
    | '/painel/anuncios/novo'
    | '/painel/empresas/$id'
    | '/painel/empresas/nova'
    | '/painel/notificacoes/preferencias'
    | '/admin/push/'
    | '/api/public/hooks/daily-blog-post'
    | '/api/public/hooks/jobs-sync'
    | '/api/public/hooks/push-scheduler'
    | '/api/public/hooks/scrape-events'
    | '/api/public/hooks/scrape-procurements'
    | '/api/public/hooks/scrape-services'
    | '/api/public/hooks/sync-bus'
    | '/api/public/hooks/sync-original'
    | '/api/public/hooks/sync-representatives'
    | '/api/public/hooks/whatsapp-opt-out'
    | '/api/public/hooks/whatsapp-weekly-digest'
    | '/api/public/push/resubscribe'
    | '/api/public/push/track'
    | '/painel/anuncios/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgoraRoute: typeof AgoraRoute
  AoVivoRoute: typeof AoVivoRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ContatoRoute: typeof ContatoRoute
  EmergenciaRoute: typeof EmergenciaRoute
  EmpregosRoute: typeof EmpregosRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  OQueFazerRoute: typeof OQueFazerRoute
  PainelRoute: typeof PainelRouteWithChildren
  PlanosRoute: typeof PlanosRoute
  PromocoesRoute: typeof PromocoesRoute
  RepresentantesRoute: typeof RepresentantesRouteWithChildren
  ReputacaoRoute: typeof ReputacaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoteiroTuristicoRoute: typeof RoteiroTuristicoRoute
  ServicosPublicosRoute: typeof ServicosPublicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TransparenciaRoute: typeof TransparenciaRoute
  TransporteRoute: typeof TransporteRouteWithChildren
  VespasianoRoute: typeof VespasianoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  CidadesSlugRoute: typeof CidadesSlugRoute
  EmpresaSlugRoute: typeof EmpresaSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  ApiPublicHooksDailyBlogPostRoute: typeof ApiPublicHooksDailyBlogPostRoute
  ApiPublicHooksJobsSyncRoute: typeof ApiPublicHooksJobsSyncRoute
  ApiPublicHooksPushSchedulerRoute: typeof ApiPublicHooksPushSchedulerRoute
  ApiPublicHooksScrapeEventsRoute: typeof ApiPublicHooksScrapeEventsRoute
  ApiPublicHooksScrapeProcurementsRoute: typeof ApiPublicHooksScrapeProcurementsRoute
  ApiPublicHooksScrapeServicesRoute: typeof ApiPublicHooksScrapeServicesRoute
  ApiPublicHooksSyncBusRoute: typeof ApiPublicHooksSyncBusRoute
  ApiPublicHooksSyncOriginalRoute: typeof ApiPublicHooksSyncOriginalRoute
  ApiPublicHooksSyncRepresentativesRoute: typeof ApiPublicHooksSyncRepresentativesRoute
  ApiPublicHooksWhatsappOptOutRoute: typeof ApiPublicHooksWhatsappOptOutRoute
  ApiPublicHooksWhatsappWeeklyDigestRoute: typeof ApiPublicHooksWhatsappWeeklyDigestRoute
  ApiPublicPushResubscribeRoute: typeof ApiPublicPushResubscribeRoute
  ApiPublicPushTrackRoute: typeof ApiPublicPushTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vespasiano': {
      id: '/vespasiano'
      path: '/vespasiano'
      fullPath: '/vespasiano'
      preLoaderRoute: typeof VespasianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transporte': {
      id: '/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof TransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-publicos': {
      id: '/servicos-publicos'
      path: '/servicos-publicos'
      fullPath: '/servicos-publicos'
      preLoaderRoute: typeof ServicosPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiro-turistico': {
      id: '/roteiro-turistico'
      path: '/roteiro-turistico'
      fullPath: '/roteiro-turistico'
      preLoaderRoute: typeof RoteiroTuristicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reputacao': {
      id: '/reputacao'
      path: '/reputacao'
      fullPath: '/reputacao'
      preLoaderRoute: typeof ReputacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes': {
      id: '/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof RepresentantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazer': {
      id: '/o-que-fazer'
      path: '/o-que-fazer'
      fullPath: '/o-que-fazer'
      preLoaderRoute: typeof OQueFazerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empregos': {
      id: '/empregos'
      path: '/empregos'
      fullPath: '/empregos'
      preLoaderRoute: typeof EmpregosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia': {
      id: '/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof EmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agora': {
      id: '/agora'
      path: '/agora'
      fullPath: '/agora'
      preLoaderRoute: typeof AgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes/': {
      id: '/representantes/'
      path: '/'
      fullPath: '/representantes/'
      preLoaderRoute: typeof RepresentantesIndexRouteImport
      parentRoute: typeof RepresentantesRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/transporte/linhas': {
      id: '/transporte/linhas'
      path: '/linhas'
      fullPath: '/transporte/linhas'
      preLoaderRoute: typeof TransporteLinhasRouteImport
      parentRoute: typeof TransporteRoute
    }
    '/representantes/ranking': {
      id: '/representantes/ranking'
      path: '/ranking'
      fullPath: '/representantes/ranking'
      preLoaderRoute: typeof RepresentantesRankingRouteImport
      parentRoute: typeof RepresentantesRoute
    }
    '/representantes/feed': {
      id: '/representantes/feed'
      path: '/feed'
      fullPath: '/representantes/feed'
      preLoaderRoute: typeof RepresentantesFeedRouteImport
      parentRoute: typeof RepresentantesRoute
    }
    '/representantes/$id': {
      id: '/representantes/$id'
      path: '/$id'
      fullPath: '/representantes/$id'
      preLoaderRoute: typeof RepresentantesIdRouteImport
      parentRoute: typeof RepresentantesRoute
    }
    '/painel/ranking': {
      id: '/painel/ranking'
      path: '/ranking'
      fullPath: '/painel/ranking'
      preLoaderRoute: typeof PainelRankingRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/promocoes': {
      id: '/painel/promocoes'
      path: '/promocoes'
      fullPath: '/painel/promocoes'
      preLoaderRoute: typeof PainelPromocoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/notificacoes': {
      id: '/painel/notificacoes'
      path: '/notificacoes'
      fullPath: '/painel/notificacoes'
      preLoaderRoute: typeof PainelNotificacoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/mensagens': {
      id: '/painel/mensagens'
      path: '/mensagens'
      fullPath: '/painel/mensagens'
      preLoaderRoute: typeof PainelMensagensRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/leads': {
      id: '/painel/leads'
      path: '/leads'
      fullPath: '/painel/leads'
      preLoaderRoute: typeof PainelLeadsRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/favoritos': {
      id: '/painel/favoritos'
      path: '/favoritos'
      fullPath: '/painel/favoritos'
      preLoaderRoute: typeof PainelFavoritosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/empresas': {
      id: '/painel/empresas'
      path: '/empresas'
      fullPath: '/painel/empresas'
      preLoaderRoute: typeof PainelEmpresasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/avaliacoes': {
      id: '/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof PainelAvaliacoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/anuncios': {
      id: '/painel/anuncios'
      path: '/anuncios'
      fullPath: '/painel/anuncios'
      preLoaderRoute: typeof PainelAnunciosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$slug': {
      id: '/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof EmpresaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empregos/premium': {
      id: '/empregos/premium'
      path: '/premium'
      fullPath: '/empregos/premium'
      preLoaderRoute: typeof EmpregosPremiumRouteImport
      parentRoute: typeof EmpregosRoute
    }
    '/empregos/$id': {
      id: '/empregos/$id'
      path: '/$id'
      fullPath: '/empregos/$id'
      preLoaderRoute: typeof EmpregosIdRouteImport
      parentRoute: typeof EmpregosRoute
    }
    '/cidades/$slug': {
      id: '/cidades/$slug'
      path: '/cidades/$slug'
      fullPath: '/cidades/$slug'
      preLoaderRoute: typeof CidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/turismo': {
      id: '/admin/turismo'
      path: '/turismo'
      fullPath: '/admin/turismo'
      preLoaderRoute: typeof AdminTurismoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/textos': {
      id: '/admin/textos'
      path: '/textos'
      fullPath: '/admin/textos'
      preLoaderRoute: typeof AdminTextosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos-publicos': {
      id: '/admin/servicos-publicos'
      path: '/servicos-publicos'
      fullPath: '/admin/servicos-publicos'
      preLoaderRoute: typeof AdminServicosPublicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scraper-vespasiano': {
      id: '/admin/scraper-vespasiano'
      path: '/scraper-vespasiano'
      fullPath: '/admin/scraper-vespasiano'
      preLoaderRoute: typeof AdminScraperVespasianoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scraper-sjl': {
      id: '/admin/scraper-sjl'
      path: '/scraper-sjl'
      fullPath: '/admin/scraper-sjl'
      preLoaderRoute: typeof AdminScraperSjlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scraper-camara-sjl': {
      id: '/admin/scraper-camara-sjl'
      path: '/scraper-camara-sjl'
      fullPath: '/admin/scraper-camara-sjl'
      preLoaderRoute: typeof AdminScraperCamaraSjlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/push': {
      id: '/admin/push'
      path: '/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AdminPushRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empregos': {
      id: '/admin/empregos'
      path: '/empregos'
      fullPath: '/admin/empregos'
      preLoaderRoute: typeof AdminEmpregosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergencia': {
      id: '/admin/emergencia'
      path: '/emergencia'
      fullPath: '/admin/emergencia'
      preLoaderRoute: typeof AdminEmergenciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duplicados': {
      id: '/admin/duplicados'
      path: '/duplicados'
      fullPath: '/admin/duplicados'
      preLoaderRoute: typeof AdminDuplicadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cidades': {
      id: '/admin/cidades'
      path: '/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AdminCidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario-editorial': {
      id: '/admin/calendario-editorial'
      path: '/calendario-editorial'
      fullPath: '/admin/calendario-editorial'
      preLoaderRoute: typeof AdminCalendarioEditorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-ai': {
      id: '/admin/blog-ai'
      path: '/blog-ai'
      fullPath: '/admin/blog-ai'
      preLoaderRoute: typeof AdminBlogAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ao-vivo': {
      id: '/admin/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/admin/ao-vivo'
      preLoaderRoute: typeof AdminAoVivoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics-anuncios': {
      id: '/admin/analytics-anuncios'
      path: '/analytics-anuncios'
      fullPath: '/admin/analytics-anuncios'
      preLoaderRoute: typeof AdminAnalyticsAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/push/': {
      id: '/admin/push/'
      path: '/'
      fullPath: '/admin/push/'
      preLoaderRoute: typeof AdminPushIndexRouteImport
      parentRoute: typeof AdminPushRoute
    }
    '/painel/notificacoes/preferencias': {
      id: '/painel/notificacoes/preferencias'
      path: '/preferencias'
      fullPath: '/painel/notificacoes/preferencias'
      preLoaderRoute: typeof PainelNotificacoesPreferenciasRouteImport
      parentRoute: typeof PainelNotificacoesRoute
    }
    '/painel/empresas/nova': {
      id: '/painel/empresas/nova'
      path: '/nova'
      fullPath: '/painel/empresas/nova'
      preLoaderRoute: typeof PainelEmpresasNovaRouteImport
      parentRoute: typeof PainelEmpresasRoute
    }
    '/painel/empresas/$id': {
      id: '/painel/empresas/$id'
      path: '/$id'
      fullPath: '/painel/empresas/$id'
      preLoaderRoute: typeof PainelEmpresasIdRouteImport
      parentRoute: typeof PainelEmpresasRoute
    }
    '/painel/anuncios/novo': {
      id: '/painel/anuncios/novo'
      path: '/novo'
      fullPath: '/painel/anuncios/novo'
      preLoaderRoute: typeof PainelAnunciosNovoRouteImport
      parentRoute: typeof PainelAnunciosRoute
    }
    '/admin/push/templates': {
      id: '/admin/push/templates'
      path: '/templates'
      fullPath: '/admin/push/templates'
      preLoaderRoute: typeof AdminPushTemplatesRouteImport
      parentRoute: typeof AdminPushRoute
    }
    '/admin/push/novo': {
      id: '/admin/push/novo'
      path: '/novo'
      fullPath: '/admin/push/novo'
      preLoaderRoute: typeof AdminPushNovoRouteImport
      parentRoute: typeof AdminPushRoute
    }
    '/admin/push/historico': {
      id: '/admin/push/historico'
      path: '/historico'
      fullPath: '/admin/push/historico'
      preLoaderRoute: typeof AdminPushHistoricoRouteImport
      parentRoute: typeof AdminPushRoute
    }
    '/admin/push/$id': {
      id: '/admin/push/$id'
      path: '/$id'
      fullPath: '/admin/push/$id'
      preLoaderRoute: typeof AdminPushIdRouteImport
      parentRoute: typeof AdminPushRoute
    }
    '/painel/anuncios/$id/editar': {
      id: '/painel/anuncios/$id/editar'
      path: '/$id/editar'
      fullPath: '/painel/anuncios/$id/editar'
      preLoaderRoute: typeof PainelAnunciosIdEditarRouteImport
      parentRoute: typeof PainelAnunciosRoute
    }
    '/api/public/push/track': {
      id: '/api/public/push/track'
      path: '/api/public/push/track'
      fullPath: '/api/public/push/track'
      preLoaderRoute: typeof ApiPublicPushTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/resubscribe': {
      id: '/api/public/push/resubscribe'
      path: '/api/public/push/resubscribe'
      fullPath: '/api/public/push/resubscribe'
      preLoaderRoute: typeof ApiPublicPushResubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-weekly-digest': {
      id: '/api/public/hooks/whatsapp-weekly-digest'
      path: '/api/public/hooks/whatsapp-weekly-digest'
      fullPath: '/api/public/hooks/whatsapp-weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWhatsappWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-opt-out': {
      id: '/api/public/hooks/whatsapp-opt-out'
      path: '/api/public/hooks/whatsapp-opt-out'
      fullPath: '/api/public/hooks/whatsapp-opt-out'
      preLoaderRoute: typeof ApiPublicHooksWhatsappOptOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-representatives': {
      id: '/api/public/hooks/sync-representatives'
      path: '/api/public/hooks/sync-representatives'
      fullPath: '/api/public/hooks/sync-representatives'
      preLoaderRoute: typeof ApiPublicHooksSyncRepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-original': {
      id: '/api/public/hooks/sync-original'
      path: '/api/public/hooks/sync-original'
      fullPath: '/api/public/hooks/sync-original'
      preLoaderRoute: typeof ApiPublicHooksSyncOriginalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-bus': {
      id: '/api/public/hooks/sync-bus'
      path: '/api/public/hooks/sync-bus'
      fullPath: '/api/public/hooks/sync-bus'
      preLoaderRoute: typeof ApiPublicHooksSyncBusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-services': {
      id: '/api/public/hooks/scrape-services'
      path: '/api/public/hooks/scrape-services'
      fullPath: '/api/public/hooks/scrape-services'
      preLoaderRoute: typeof ApiPublicHooksScrapeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-procurements': {
      id: '/api/public/hooks/scrape-procurements'
      path: '/api/public/hooks/scrape-procurements'
      fullPath: '/api/public/hooks/scrape-procurements'
      preLoaderRoute: typeof ApiPublicHooksScrapeProcurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-events': {
      id: '/api/public/hooks/scrape-events'
      path: '/api/public/hooks/scrape-events'
      fullPath: '/api/public/hooks/scrape-events'
      preLoaderRoute: typeof ApiPublicHooksScrapeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-scheduler': {
      id: '/api/public/hooks/push-scheduler'
      path: '/api/public/hooks/push-scheduler'
      fullPath: '/api/public/hooks/push-scheduler'
      preLoaderRoute: typeof ApiPublicHooksPushSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/jobs-sync': {
      id: '/api/public/hooks/jobs-sync'
      path: '/api/public/hooks/jobs-sync'
      fullPath: '/api/public/hooks/jobs-sync'
      preLoaderRoute: typeof ApiPublicHooksJobsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-blog-post': {
      id: '/api/public/hooks/daily-blog-post'
      path: '/api/public/hooks/daily-blog-post'
      fullPath: '/api/public/hooks/daily-blog-post'
      preLoaderRoute: typeof ApiPublicHooksDailyBlogPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPushRouteChildren {
  AdminPushIdRoute: typeof AdminPushIdRoute
  AdminPushHistoricoRoute: typeof AdminPushHistoricoRoute
  AdminPushNovoRoute: typeof AdminPushNovoRoute
  AdminPushTemplatesRoute: typeof AdminPushTemplatesRoute
  AdminPushIndexRoute: typeof AdminPushIndexRoute
}

const AdminPushRouteChildren: AdminPushRouteChildren = {
  AdminPushIdRoute: AdminPushIdRoute,
  AdminPushHistoricoRoute: AdminPushHistoricoRoute,
  AdminPushNovoRoute: AdminPushNovoRoute,
  AdminPushTemplatesRoute: AdminPushTemplatesRoute,
  AdminPushIndexRoute: AdminPushIndexRoute,
}

const AdminPushRouteWithChildren = AdminPushRoute._addFileChildren(
  AdminPushRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsAnunciosRoute: typeof AdminAnalyticsAnunciosRoute
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminAoVivoRoute: typeof AdminAoVivoRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBlogAiRoute: typeof AdminBlogAiRoute
  AdminCalendarioEditorialRoute: typeof AdminCalendarioEditorialRoute
  AdminCidadesRoute: typeof AdminCidadesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDuplicadosRoute: typeof AdminDuplicadosRoute
  AdminEmergenciaRoute: typeof AdminEmergenciaRoute
  AdminEmpregosRoute: typeof AdminEmpregosRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminPushRoute: typeof AdminPushRouteWithChildren
  AdminQaRoute: typeof AdminQaRoute
  AdminScraperCamaraSjlRoute: typeof AdminScraperCamaraSjlRoute
  AdminScraperSjlRoute: typeof AdminScraperSjlRoute
  AdminScraperVespasianoRoute: typeof AdminScraperVespasianoRoute
  AdminServicosPublicosRoute: typeof AdminServicosPublicosRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminTextosRoute: typeof AdminTextosRoute
  AdminTurismoRoute: typeof AdminTurismoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsAnunciosRoute: AdminAnalyticsAnunciosRoute,
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminAoVivoRoute: AdminAoVivoRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBlogAiRoute: AdminBlogAiRoute,
  AdminCalendarioEditorialRoute: AdminCalendarioEditorialRoute,
  AdminCidadesRoute: AdminCidadesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDuplicadosRoute: AdminDuplicadosRoute,
  AdminEmergenciaRoute: AdminEmergenciaRoute,
  AdminEmpregosRoute: AdminEmpregosRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminPushRoute: AdminPushRouteWithChildren,
  AdminQaRoute: AdminQaRoute,
  AdminScraperCamaraSjlRoute: AdminScraperCamaraSjlRoute,
  AdminScraperSjlRoute: AdminScraperSjlRoute,
  AdminScraperVespasianoRoute: AdminScraperVespasianoRoute,
  AdminServicosPublicosRoute: AdminServicosPublicosRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminTextosRoute: AdminTextosRoute,
  AdminTurismoRoute: AdminTurismoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmpregosRouteChildren {
  EmpregosIdRoute: typeof EmpregosIdRoute
  EmpregosPremiumRoute: typeof EmpregosPremiumRoute
}

const EmpregosRouteChildren: EmpregosRouteChildren = {
  EmpregosIdRoute: EmpregosIdRoute,
  EmpregosPremiumRoute: EmpregosPremiumRoute,
}

const EmpregosRouteWithChildren = EmpregosRoute._addFileChildren(
  EmpregosRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface PainelAnunciosRouteChildren {
  PainelAnunciosNovoRoute: typeof PainelAnunciosNovoRoute
  PainelAnunciosIdEditarRoute: typeof PainelAnunciosIdEditarRoute
}

const PainelAnunciosRouteChildren: PainelAnunciosRouteChildren = {
  PainelAnunciosNovoRoute: PainelAnunciosNovoRoute,
  PainelAnunciosIdEditarRoute: PainelAnunciosIdEditarRoute,
}

const PainelAnunciosRouteWithChildren = PainelAnunciosRoute._addFileChildren(
  PainelAnunciosRouteChildren,
)

interface PainelEmpresasRouteChildren {
  PainelEmpresasIdRoute: typeof PainelEmpresasIdRoute
  PainelEmpresasNovaRoute: typeof PainelEmpresasNovaRoute
}

const PainelEmpresasRouteChildren: PainelEmpresasRouteChildren = {
  PainelEmpresasIdRoute: PainelEmpresasIdRoute,
  PainelEmpresasNovaRoute: PainelEmpresasNovaRoute,
}

const PainelEmpresasRouteWithChildren = PainelEmpresasRoute._addFileChildren(
  PainelEmpresasRouteChildren,
)

interface PainelNotificacoesRouteChildren {
  PainelNotificacoesPreferenciasRoute: typeof PainelNotificacoesPreferenciasRoute
}

const PainelNotificacoesRouteChildren: PainelNotificacoesRouteChildren = {
  PainelNotificacoesPreferenciasRoute: PainelNotificacoesPreferenciasRoute,
}

const PainelNotificacoesRouteWithChildren =
  PainelNotificacoesRoute._addFileChildren(PainelNotificacoesRouteChildren)

interface PainelRouteChildren {
  PainelAnunciosRoute: typeof PainelAnunciosRouteWithChildren
  PainelAvaliacoesRoute: typeof PainelAvaliacoesRoute
  PainelEmpresasRoute: typeof PainelEmpresasRouteWithChildren
  PainelFavoritosRoute: typeof PainelFavoritosRoute
  PainelLeadsRoute: typeof PainelLeadsRoute
  PainelMensagensRoute: typeof PainelMensagensRoute
  PainelNotificacoesRoute: typeof PainelNotificacoesRouteWithChildren
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelPromocoesRoute: typeof PainelPromocoesRoute
  PainelRankingRoute: typeof PainelRankingRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAnunciosRoute: PainelAnunciosRouteWithChildren,
  PainelAvaliacoesRoute: PainelAvaliacoesRoute,
  PainelEmpresasRoute: PainelEmpresasRouteWithChildren,
  PainelFavoritosRoute: PainelFavoritosRoute,
  PainelLeadsRoute: PainelLeadsRoute,
  PainelMensagensRoute: PainelMensagensRoute,
  PainelNotificacoesRoute: PainelNotificacoesRouteWithChildren,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelPromocoesRoute: PainelPromocoesRoute,
  PainelRankingRoute: PainelRankingRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

interface RepresentantesRouteChildren {
  RepresentantesIdRoute: typeof RepresentantesIdRoute
  RepresentantesFeedRoute: typeof RepresentantesFeedRoute
  RepresentantesRankingRoute: typeof RepresentantesRankingRoute
  RepresentantesIndexRoute: typeof RepresentantesIndexRoute
}

const RepresentantesRouteChildren: RepresentantesRouteChildren = {
  RepresentantesIdRoute: RepresentantesIdRoute,
  RepresentantesFeedRoute: RepresentantesFeedRoute,
  RepresentantesRankingRoute: RepresentantesRankingRoute,
  RepresentantesIndexRoute: RepresentantesIndexRoute,
}

const RepresentantesRouteWithChildren = RepresentantesRoute._addFileChildren(
  RepresentantesRouteChildren,
)

interface TransporteRouteChildren {
  TransporteLinhasRoute: typeof TransporteLinhasRoute
}

const TransporteRouteChildren: TransporteRouteChildren = {
  TransporteLinhasRoute: TransporteLinhasRoute,
}

const TransporteRouteWithChildren = TransporteRoute._addFileChildren(
  TransporteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgoraRoute: AgoraRoute,
  AoVivoRoute: AoVivoRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ContatoRoute: ContatoRoute,
  EmergenciaRoute: EmergenciaRoute,
  EmpregosRoute: EmpregosRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  OQueFazerRoute: OQueFazerRoute,
  PainelRoute: PainelRouteWithChildren,
  PlanosRoute: PlanosRoute,
  PromocoesRoute: PromocoesRoute,
  RepresentantesRoute: RepresentantesRouteWithChildren,
  ReputacaoRoute: ReputacaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoteiroTuristicoRoute: RoteiroTuristicoRoute,
  ServicosPublicosRoute: ServicosPublicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TransparenciaRoute: TransparenciaRoute,
  TransporteRoute: TransporteRouteWithChildren,
  VespasianoRoute: VespasianoRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  CidadesSlugRoute: CidadesSlugRoute,
  EmpresaSlugRoute: EmpresaSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  ApiPublicHooksDailyBlogPostRoute: ApiPublicHooksDailyBlogPostRoute,
  ApiPublicHooksJobsSyncRoute: ApiPublicHooksJobsSyncRoute,
  ApiPublicHooksPushSchedulerRoute: ApiPublicHooksPushSchedulerRoute,
  ApiPublicHooksScrapeEventsRoute: ApiPublicHooksScrapeEventsRoute,
  ApiPublicHooksScrapeProcurementsRoute: ApiPublicHooksScrapeProcurementsRoute,
  ApiPublicHooksScrapeServicesRoute: ApiPublicHooksScrapeServicesRoute,
  ApiPublicHooksSyncBusRoute: ApiPublicHooksSyncBusRoute,
  ApiPublicHooksSyncOriginalRoute: ApiPublicHooksSyncOriginalRoute,
  ApiPublicHooksSyncRepresentativesRoute:
    ApiPublicHooksSyncRepresentativesRoute,
  ApiPublicHooksWhatsappOptOutRoute: ApiPublicHooksWhatsappOptOutRoute,
  ApiPublicHooksWhatsappWeeklyDigestRoute:
    ApiPublicHooksWhatsappWeeklyDigestRoute,
  ApiPublicPushResubscribeRoute: ApiPublicPushResubscribeRoute,
  ApiPublicPushTrackRoute: ApiPublicPushTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
